version: '3.8'

services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    restart: always
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: instmois/foodgram-backend:latest
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    volumes:
      - backend_static:/app/backend/static/
      - backend_media:/app/backend/media/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env
    expose:
      - "8000" 

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_static:/app/build

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/usr/share/nginx/html/web/build/:ro
      - backend_static:/usr/share/nginx/html/static/:ro
      - backend_media:/usr/share/nginx/html/media/:ro
      - ../docs/:/usr/share/nginx/html/api/docs/:ro
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  backend_static:
  backend_media:
  frontend_static: